
set(ENABLED_GEMS
    Subyellort
    Atom
    AudioSystem
    
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    Multiplayer
    PhysX
    PrimitiveAssets
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    AtomLyIntegration
    AtomTressFX
    PrefabBuilder
    Terrain
    UiBasics
)
